Ejercicios en clase de Andrea
Serk352/built-in-Objects pull request #6
Opened 2020-02-14 22:28 UTC by andrea7896

2020-02-14 22:51 UTC, Serk352 requested changes
Vamos bien, solo faltan algunos detalles y algunos (varios) ";" jaja

2020-02-14 22:51 UTC, Serk352 commented on main.js
> +    if(Number.isInteger(numero)){
yo digo que un ternario funcionaría bien aquí en lugar de if/else

2020-02-14 22:51 UTC, Serk352 commented on main.js
> +    console.log(value.toString().length)
aquí se nos olvidó el ";"  :(

2020-02-14 22:51 UTC, Serk352 commented on main.js
> +Object.keys(usuario),Object.values(usuario));
aquí como que algo no me cuadra, si está bien?

2020-02-14 22:51 UTC, Serk352 commented on main.js
> +ObjectFun(usuario)
";" ?

2020-02-14 22:51 UTC, Serk352 commented on main.js
> +var sum = new Function('a','b','c','return a + b + c');
yo creo que esta variable se puede evitar

2020-02-14 22:51 UTC, Serk352 commented on main.js
> +    var dif = array.length - desireL;
U_U nop, yo digo que cheques bien esta parte

2020-02-14 22:51 UTC, Serk352 commented on main.js
> +    console.log(new Date()," ",Date.now());
yo digo que sería mejor un template string

2020-02-14 22:51 UTC, Serk352 commented on main.js
> +RegExpFun("Mola","N")
";" ?

2020-02-14 22:51 UTC, Serk352 commented on main.js
> +desplegar(Usuario);
notese que segun tu declararion desplegar recibe un array, y aqui lo estamos alimentando con Usuario y Usuario es un ... ?

2020-02-15 05:33 UTC, andrea7896 commented on main.js
> +    console.log(value.toString().length)
Java me tenia obligada a usar ";" ahora que conozco JavaScript senti demasiada libertad que los olvide xD,  lo voy a corregir :3

2020-02-15 06:09 UTC, andrea7896 commented on main.js
> +Object.keys(usuario),Object.values(usuario));
Repeti el Object.keys(usuario), solo borre uno

2020-02-15 06:47 UTC, andrea7896 commented on main.js
> +    var dif = array.length - desireL;
Esta todo mal o el como mando a llamar a la funcion? D:

2020-02-15 06:48 UTC, andrea7896 commented on main.js
> +desplegar(Usuario);
Objeto* UuU

2020-02-15 07:06 UTC, andrea7896 commented on main.js
> +    var dif = array.length - desireL;
function ArrayDesire(array,desireL,template){
    var dif = array.length - desireL;
    if(dif === 1){
        array.push(template);
        return array;
    }else if(dif > 1){
        return "El array es mayor por "+dif;
    }else{
        return "El array es menor por "+Math.abs(dif);
    }

}

console.log(ArrayDesire(["Hola","juan"],4,"juan"));

2020-02-16 18:32 UTC, Serk352 commented on main.js
> +    console.log(value.toString().length)
Jaja recuerda que el hecho de que "no sea necesario" no significa que no debamos, el viernes que hablemos de buenas practicas, veremos el porqué :D

2020-02-16 18:33 UTC, Serk352 commented on main.js
> +Object.keys(usuario),Object.values(usuario));
ok :D

2020-02-16 18:36 UTC, Serk352 commented on main.js
> +    var dif = array.length - desireL;
cuidado con ese Math.abs

2020-02-16 18:36 UTC, Serk352 commented on main.js
> +desplegar(Usuario);
yep jajaja

2026-04-21 03:12 UTC, closed without merging